# Walmart Sales Forecasting Project

## Phase 1: Data Understanding

### Objective
The objective of this notebook is to understand the dataset before performing any data cleaning or analysis.

### Business Problem
Walmart wants to forecast future sales using historical sales data to improve inventory management, staffing, and business planning.

### Dataset
Source: Kaggle

### Analyst
Karishma

### Date
20-07-2026

# Step 1: Import Required Libraries

In [2]:
# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import plotly.express as px

# Step 2: Load the Dataset

In [3]:
df = pd.read_excel("../data/raw/walmart.xlsx")

In [4]:
# Display the first 5 rows of the dataset
df.head()

,Order ID,Order Date,Ship Date,Customer Name,Country,City,State,Category,Product Name,Sales,Quantity,Profit
0,CA-2013-138688,2013-06-13,2013-06-17,Darrin Van Huff,United States,Los Angeles,California,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,6.8714
1,CA-2011-115812,2011-06-09,2011-06-14,Brosina Hoffman,United States,Los Angeles,California,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,14.1694
2,CA-2011-115812,2011-06-09,2011-06-14,Brosina Hoffman,United States,Los Angeles,California,Art,Newell 322,7.280,4,1.9656
3,CA-2011-115812,2011-06-09,2011-06-14,Brosina Hoffman,United States,Los Angeles,California,Phones,Mitel 5320 IP Phone VoIP phone,907.152,4,90.7152
4,CA-2011-115812,2011-06-09,2011-06-14,Brosina Hoffman,United States,Los Angeles,California,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,5.7825

# Step 3: Inspect the Last Five Rows

In [5]:
df.tail()

,Order ID,Order Date,Ship Date,Customer Name,Country,City,State,Category,Product Name,Sales,Quantity,Profit
3198,CA-2013-125794,2013-09-30,2013-10-04,Maris LaWare,United States,Los Angeles,California,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,15.2208
3199,CA-2014-121258,2014-02-27,2014-03-04,Dave Brooks,United States,Costa Mesa,California,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,15.6332
3200,CA-2014-121258,2014-02-27,2014-03-04,Dave Brooks,United States,Costa Mesa,California,Phones,Aastra 57i VoIP phone,258.576,2,19.3932
3201,CA-2014-121258,2014-02-27,2014-03-04,Dave Brooks,United States,Costa Mesa,California,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,13.3200
3202,CA-2014-119914,2014-05-05,2014-05-10,Chris Cortes,United States,Westminster,California,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,72.9480

# Step 4: Check Dataset Dimensions

In [6]:
df.shape

(3203, 12)

# Step 5: Display Column Names

In [7]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Customer Name', 'Country',
       'City', 'State', 'Category', 'Product Name', 'Sales', 'Quantity',
       'Profit'],
      dtype='str')

# Step 6: Check Data Types

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3203 entries, 0 to 3202
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       3203 non-null   str
 1   Order Date     3203 non-null   datetime64[us]
 2   Ship Date      3203 non-null   datetime64[us]
 3   Customer Name  3203 non-null   str
 4   Country        3203 non-null   str
 5   City           3203 non-null   str
 6   State          3203 non-null   str
 7   Category       3203 non-null   str
 8   Product Name   3203 non-null   str
 9   Sales          3203 non-null   float64
 10  Quantity       3203 non-null   int64
 11  Profit         3203 non-null   float64
dtypes: datetime64[us](2), float64(2), int64(1), str(7)
memory usage: 300.4 KB

# Step 7: Generate Summary Statistics

In [9]:
df.describe()

,Order Date,Ship Date,Sales,Quantity,Profit
count,3203,3203,3203.000000,3203.000000,3203.000000
mean,2013-05-10 03:06:07.530440,2013-05-14 01:25:25.195129,226.493233,3.828910,33.849032
min,2011-01-07 00:00:00,2011-01-09 00:00:00,0.990000,1.000000,-3399.980000
25%,2012-05-22 00:00:00,2012-05-26 00:00:00,19.440000,2.000000,3.852000
50%,2013-07-22 00:00:00,2013-07-25 00:00:00,60.840000,3.000000,11.166400
75%,2014-05-23 00:00:00,2014-05-27 00:00:00,215.809000,5.000000,33.000400
max,2014-12-31 00:00:00,2015-01-06 00:00:00,13999.960000,14.000000,6719.980800
std,NaN,NaN,524.876877,2.260947,174.109081

# Step 8: Summary of Categorical Variables

In [11]:
df.describe(include="object")

/var/folders/pt/mg7qrs3d7853_jbrc_5rgh8w0000gn/T/ipykernel_2134/702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Order ID,Customer Name,Country,City,State,Category,Product Name
count,3203,3203,3203,3203,3203,3203,3203
unique,1611,686,1,169,11,17,1494
top,CA-2013-165330,William Brown,United States,Los Angeles,California,Binders,Staples
freq,11,24,3203,747,2001,471,60

| Column Name | Data Type | Description |
|-------------|-----------|-------------|
| Order ID | Text | Unique identifier for each order |
| Order Date | Date | Date the order was placed |
| Ship Date | Date | Date the order was shipped |
| Customer Name | Text | Name of the customer |
| Country | Text | Customer's country |
| City | Text | Customer's city |
| State | Text | Customer's state |
| Category | Text | Product category |
| Product Name | Text | Product sold |
| Sales | Numeric | Revenue from the sale |
| Quantity | Numeric | Number of units sold |
| Profit | Numeric | Profit earned from the sale |