# Walmart Sales Forecasting Project

## Notebook 05 – Feature Engineering

### Objective

Create new features from the daily sales dataset that will improve machine learning model performance for forecasting.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("../data/processed/daily_sales.xlsx")

In [3]:
df.head()

       index  Sales
0 2011-01-07  19.44
1 2011-01-08    NaN
2 2011-01-09    NaN
3 2011-01-10    NaN
4 2011-01-11    NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1455 entries, 0 to 1454
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   1455 non-null   datetime64[us]
 1   Sales   845 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 22.9 KB

In [5]:
df.shape

(1455, 2)

In [6]:
df.columns

Index(['index', 'Sales'], dtype='str')

In [7]:
df.rename(columns={"index": "Order Date"}, inplace=True)

In [8]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [9]:
df["Sales"] = df["Sales"].fillna(0)

In [10]:
df.isnull().sum()

Order Date    0
Sales         0
dtype: int64

In [11]:
df["Year"] = df["Order Date"].dt.year

df["Quarter"] = df["Order Date"].dt.quarter

df["Month"] = df["Order Date"].dt.month

df["Week"] = df["Order Date"].dt.isocalendar().week.astype(int)

df["Day"] = df["Order Date"].dt.day

df["DayOfWeek"] = df["Order Date"].dt.dayofweek

df["DayName"] = df["Order Date"].dt.day_name()

df["IsWeekend"] = (df["DayOfWeek"] >= 5).astype(int)

In [12]:
df["Lag_1"] = df["Sales"].shift(1)

df["Lag_7"] = df["Sales"].shift(7)

df["Lag_30"] = df["Sales"].shift(30)

In [13]:
df["Rolling_Mean_7"] = df["Sales"].rolling(7).mean()

df["Rolling_Mean_30"] = df["Sales"].rolling(30).mean()

df["Rolling_STD_7"] = df["Sales"].rolling(7).std()

In [14]:
df["Expanding_Mean"] = df["Sales"].expanding().mean()

In [15]:
df["Month_Sin"] = np.sin(2*np.pi*df["Month"]/12)

df["Month_Cos"] = np.cos(2*np.pi*df["Month"]/12)

df["Day_Sin"] = np.sin(2*np.pi*df["DayOfWeek"]/7)

df["Day_Cos"] = np.cos(2*np.pi*df["DayOfWeek"]/7)

In [16]:
df.isnull().sum()

Order Date          0
Sales               0
Year                0
Quarter             0
Month               0
Week                0
Day                 0
DayOfWeek           0
DayName             0
IsWeekend           0
Lag_1               1
Lag_7               7
Lag_30             30
Rolling_Mean_7      6
Rolling_Mean_30    29
Rolling_STD_7       6
Expanding_Mean      0
Month_Sin           0
Month_Cos           0
Day_Sin             0
Day_Cos             0
dtype: int64

In [17]:
df = df.dropna().reset_index(drop=True)

In [18]:
df.isnull().sum()

Order Date         0
Sales              0
Year               0
Quarter            0
Month              0
Week               0
Day                0
DayOfWeek          0
DayName            0
IsWeekend          0
Lag_1              0
Lag_7              0
Lag_30             0
Rolling_Mean_7     0
Rolling_Mean_30    0
Rolling_STD_7      0
Expanding_Mean     0
Month_Sin          0
Month_Cos          0
Day_Sin            0
Day_Cos            0
dtype: int64

In [19]:
df.head()

,Order Date,Sales,Year,Quarter,Month,Week,Day,DayOfWeek,DayName,IsWeekend,...,Lag_7,Lag_30,Rolling_Mean_7,Rolling_Mean_30,Rolling_STD_7,Expanding_Mean,Month_Sin,Month_Cos,Day_Sin,Day_Cos
0,2011-02-06,0.00,2011,1,2,5,6,6,Sunday,1,...,0.000,19.44,76.358857,105.437633,109.021650,102.663516,0.866025,0.5,-0.781831,0.623490
1,2011-02-07,0.00,2011,1,2,6,7,0,Monday,0,...,0.000,0.00,76.358857,105.437633,109.021650,99.455281,0.866025,0.5,0.000000,1.000000
2,2011-02-08,0.00,2011,1,2,6,8,1,Tuesday,0,...,290.666,0.00,34.835143,105.437633,56.491758,96.441485,0.866025,0.5,0.781831,0.623490
3,2011-02-09,14.56,2011,1,2,6,9,2,Wednesday,0,...,0.000,0.00,36.915143,105.922967,55.249769,94.033206,0.866025,0.5,0.974928,-0.222521
4,2011-02-10,0.00,2011,1,2,6,10,3,Thursday,0,...,12.350,0.00,35.150857,105.922967,56.351152,91.346543,0.866025,0.5,0.433884,-0.900969

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1425 entries, 0 to 1424
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order Date       1425 non-null   datetime64[us]
 1   Sales            1425 non-null   float64
 2   Year             1425 non-null   int32
 3   Quarter          1425 non-null   int32
 4   Month            1425 non-null   int32
 5   Week             1425 non-null   int64
 6   Day              1425 non-null   int32
 7   DayOfWeek        1425 non-null   int32
 8   DayName          1425 non-null   str
 9   IsWeekend        1425 non-null   int64
 10  Lag_1            1425 non-null   float64
 11  Lag_7            1425 non-null   float64
 12  Lag_30           1425 non-null   float64
 13  Rolling_Mean_7   1425 non-null   float64
 14  Rolling_Mean_30  1425 non-null   float64
 15  Rolling_STD_7    1425 non-null   float64
 16  Expanding_Mean   1425 non-null   float64
 17  Month_Sin        1425 non-null   float64
 18  Month_Cos        1425 non-null   float64
 19  Day_Sin          1425 non-null   float64
 20  Day_Cos          1425 non-null   float64
dtypes: datetime64[us](1), float64(12), int32(5), int64(2), str(1)
memory usage: 206.1 KB

In [21]:
df.shape

(1425, 21)

In [22]:
df = df.drop(columns=["DayName"], errors="ignore")

df.to_excel("../data/processed/sales_feature_engineered.xlsx", index=False)

print("✅ sales_feature_engineered.xlsx saved successfully!")

✅ sales_feature_engineered.xlsx saved successfully!

# Business Insights

- Calendar features capture seasonality.
- Lag features provide historical sales information.
- Rolling statistics smooth short-term fluctuations.
- Expanding mean captures long-term sales trends.
- Cyclical features help machine learning models understand repeating time patterns.
- The dataset is now ready for model building.

In [23]:
import os

print(os.getcwd())

/Users/karishma/Documents/Sales_Forecasting_Project/notebooks

In [24]:
df.to_excel("../data/processed/sales_feature_engineered.xlsx", index=False)

In [25]:
print(df.columns)

Index(['Order Date', 'Sales', 'Year', 'Quarter', 'Month', 'Week', 'Day',
       'DayOfWeek', 'IsWeekend', 'Lag_1', 'Lag_7', 'Lag_30', 'Rolling_Mean_7',
       'Rolling_Mean_30', 'Rolling_STD_7', 'Expanding_Mean', 'Month_Sin',
       'Month_Cos', 'Day_Sin', 'Day_Cos'],
      dtype='str')